language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
env: CI_OPTS=--stacktrace
install: "/bin/true"
script: "./gradlew build -d"
deploy:
  provider: heroku
  api_key:
    secure: QHh7DigLF2moyfOJiJX6T9LDGYx+detUvUudqmsNSEKOwo5r0CISKKjcSnRu1YJRUq2if6yuVgVypT73ca//oR77RNTrIPHE/92UY0ziYEezJFkyFeUcBMOxLs2tngrQj6lQQ4hXaI040Mz2gSB/Z4gEUCociQCBa9nUUGz78arRdc4X1YPuqcRKuTXCaK7Vj4jCk29zBcBzutu3hpalf4IWd8UZfvlXgvbaFFVAXEJHNzEDXNNNvayxgvf8RjaPgsDaJw+BXGDkQtzJoWQpfe2pYgybanu1ERrfjX5cHPPZqKEOpbfTSNcd54aU79Sfe/ld9UidgKP2sLCU0xxSAzEvsHA98qWLH8zcp/9ABT715N3WfyHW2bDCTCsimgRFy9Qdx8wQ4Oa88yJMLHU9gN8fBZLTPf4lrd69LDCrxZPR7zw/CdneMsC7v7EjCY7EgoJlvzASkwpCM0RKg7JIleT+A8Sz3zoOqJeOCUO2bsVAbUETBHumNsUjaLq62lO5wigHRA4WJJJSU5iwi7cznF3HCfEZBcnJYOu/Ra5q3ynQftSIFfS1QuNdwESItl1AsITSuje4oiKHTD527wGPfuL1C7zJaB6v+TVi+LmqqERH2SxhkG90GHFo8Zv4ibYIghCZO+PORxqKue6VMoa3GvCr3QXpVVRaQ3elU2uSf98=
  app: agile-journey-9583
