language:  java
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

env: GRADLE_OPTS=-Dorg.gradle.daemon=true
env: CI_OPTS=--stacktrace

install: /bin/true
script: "./gradlew -x stage"

deploy:
  provider: heroku
  api_key:
    secure: BbgJUQKfqlGchnFNAeS4IhTqUzNeavc0WDWNH8BzZaX8NulpjWUG2K8wVWh27RQpp9jBjuMeDSC08Z99geGu+i4bw69zVkZpzQ8sryxPy9Z8vV6xlEuO3HkaZHyz+ldIiAXr0SeUMdtiMruSIk/YCeFwKc2bKw89LkZyfalylNSoLr8GmGB+fLD8PcOQPAJQNQTvTlLTefGJjW7JWhshDIWM3BWsXBqlvLNjI93YRW1HrmN257OGF540n9qNQApsP1dML/dZsESkUFaX2PdH2uI7vH3orMlmwAXc/7wQNmaWdLu+IRdv08TZk17K9vWOuMFYYZBejh1IR7FuYVlpfJsK6b1NZXUofRl8vG4G013em/LF333haBXugIQ3SWPPPkzvn1Itp7VTbU+cc75b+VFwughEZinFDCsFZte9TN4rJAHdGVKwcp+aECbjP0ZOB0xqRJpky/nVdqdNUpgqnskO/CIjk2ZoNLAB9fkU5CP1TM+bc72BEiNFrvneiKOFnf4bjweMla0MyI/KwpHkuwzPvVah49rP3AnSSiS21avxUw6ZUoVPbcCNSQH3l6zAg9V4XYW+SDqkjdxlafwE5gA4e2oHU15h2O4EFgvsV9K/FNUWS0UkyZcpF02pTflikcA5VO6rZsAFGLIxVPZkw/No4LMFuAnmxWD8KeC94nE=
  app: agile-journey-9583
  on:
    repo: nemonik/java-stix-validator
