/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'walsh' at '5/20/15 11:48 AM' with Gradle 2.3
 *
 * @author walsh, @date 5/20/15 11:48 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
